#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null && pwd)"
SCRIPT_NAME=$1
BIN_DIR="$SCRIPT_DIR/node_modules/.bin"
SCRIPT="$BIN_DIR/$SCRIPT_NAME"

if [ -s "$SCRIPT" ]; then
  shift
  "$SCRIPT" "$@"
else
  npm run -- "$@"
fi
