#!/usr/bin/env bash
# vim: ai ts=2 sw=2 et sts=2 ft=sh
# vim: autoindent tabstop=2 shiftwidth=2 expandtab softtabstop=2 filetype=sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null && pwd)"
SCRIPT_NAME=$1
BIN_DIR="$SCRIPT_DIR/node_modules/.bin"
SCRIPT="$BIN_DIR/$SCRIPT_NAME"

if [ -s "$SCRIPT" ]; then
  shift
  "$SCRIPT" "$@"
else
  npm run -- "$@"
fi
